name:                myers-diff
version:             0.3.0.1
github:              "codedownio/myers-diff"
author:              "Tom McLaughlin"
maintainer:          "tom@codedown.io"
copyright:           "2023 Tom McLaughlin"
license:             BSD3

extra-source-files:
- README.md
- CHANGELOG.md

description:         Please see the README on GitHub at <https://github.com/codedownio/myers-diff#readme>

dependencies:
- base >= 4.7 && < 5
- containers
- exceptions
- primitive
- text
- vector

flags:
  uni_myers:
    manual: true
    default: false
    description: Use the diff implementation from the "uni-util" package (buggy). This causes LGPL code to be included.
  diff:
    manual: true
    default: false
    description: Include the diff implementation from the "Diff" package

when:
- condition: flag(uni_myers)
  cpp-options: -DUNI_MYERS
- condition: flag(diff)
  cpp-options: -DDIFF

default-extensions:
- OverloadedStrings
- QuasiQuotes
- NamedFieldPuns
- RecordWildCards
- ScopedTypeVariables
- FlexibleContexts
- FlexibleInstances
- LambdaCase
- ConstraintKinds
- ViewPatterns
- TupleSections
- MultiWayIf
- NumericUnderscores
- MultiParamTypeClasses

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src
  when:
  - condition: flag(uni_myers)
    source-dirs: src-uni-myers
    exposed-modules:
    - Data.Diff.UniMyers
    dependencies:
    - array
  - condition: flag(diff)
    source-dirs: src-diff
    exposed-modules:
    - Data.Diff.Diff
    dependencies:
    - Diff

# executables:
#   myers-diff:
#     main: Main.hs
#     source-dirs:
#     - app
#     - test-lib
#     ghc-options:
#     - -threaded
#     - -rtsopts
#     - -with-rtsopts=-N
#     - -O2
#     dependencies:
#     - deepseq
#     - myers-diff
#     - string-interpolate
#     - text-rope
#     - QuickCheck
#     - quickcheck-instances

tests:
  myers-diff-test:
    main:                Spec.hs
    source-dirs:
    - test
    - test-lib
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O2
    dependencies:
    - criterion
    - deepseq
    - myers-diff
    - sandwich
    - sandwich-quickcheck
    - string-interpolate
    - text-rope
    - QuickCheck
    - quickcheck-instances
    when:
    - condition: flag(uni_myers)
      source-dirs: test-uni-myers
    - condition: flag(diff)
      source-dirs: test-diff

benchmarks:
  myers-diff-criterion-small-inserts:
    main:                Main.hs
    source-dirs:
    - bench-criterion-small-inserts
    - test-lib
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O2
    dependencies:
    - criterion
    - deepseq
    - myers-diff
    - QuickCheck
    - quickcheck-instances
    - string-interpolate
    - text-rope

  myers-diff-criterion-small-deletes:
    main:                Main.hs
    source-dirs:
    - bench-criterion-small-deletes
    - test-lib
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O2
    dependencies:
    - criterion
    - deepseq
    - myers-diff
    - QuickCheck
    - quickcheck-instances
    - string-interpolate
    - text-rope

  myers-diff-weigh:
    main:                Main.hs
    source-dirs:
    - bench-weigh
    - test-lib
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O2
    dependencies:
    - criterion
    - deepseq
    - myers-diff
    - QuickCheck
    - quickcheck-instances
    - string-interpolate
    - text-rope
    - weigh

  micro:
    main:                Main.hs
    source-dirs:
    - bench-micro
    - test-lib
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O2
    dependencies:
    - criterion
    - deepseq
    - myers-diff
    - QuickCheck
    - quickcheck-instances
    - string-interpolate
    - text-rope
    - weigh
