name: CI

on:
  pull_request:
  push:

jobs:
  cabal:
    name: cabal / ${{ matrix.os }} / ghc ${{ matrix.ghc }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
        - ubuntu-latest
        - macOS-latest
        # - windows-latest
        ghc:
        - "8.10.7"
        - "9.0.2"
        - "9.2.8"
        - "9.4.8"
        - "9.6.7"
        - "9.8.4"
        - "9.10.1"
        exclude:
        # These don't work on GitHub CI anymore because they need llvm@13, which became
        # disabled on 12/31/2024
        - os: macOS-latest
          ghc: 8.10.7
        - os: macOS-latest
          ghc: 9.0.2

    steps:
    - uses: actions/checkout@v3

    - uses: haskell-actions/setup@v2
      id: setup-haskell-cabal
      name: Setup Haskell
      with:
        ghc-version: ${{ matrix.ghc }}
        cabal-version: "latest"

    - name: Freeze
      run: |
        cabal freeze

    - uses: actions/cache@v3
      name: Cache ~/.cabal/store
      with:
        path: ${{ steps.setup-haskell-cabal.outputs.cabal-store }}
        key: ${{ runner.os }}-${{ matrix.ghc }}-${{ hashFiles('cabal.project.freeze') }}

    - name: Build
      run: |
        cabal configure --enable-tests --enable-benchmarks --test-show-details=direct
        cabal build all

    - name: Test
      run: |
        cabal test all

  stack:
    name: ${{ matrix.os }} / ${{ matrix.stack-yaml }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
        - ubuntu-latest
        - macOS-latest
        # - windows-latest
        stack-yaml:
        - stack/stack-8.10.7.yaml
        - stack/stack-9.0.2.yaml
        - stack/stack-9.2.8.yaml
        - stack/stack-9.4.8.yaml
        - stack/stack-9.6.7.yaml
        - stack/stack-9.8.4.yaml
        - stack/stack-9.10.1.yaml

    steps:
    - uses: actions/checkout@v3

    - uses: haskell-actions/setup@v2
      name: Setup Haskell Stack
      with:
        stack-version: "latest"
        enable-stack: true

    - uses: actions/cache@v3
      name: Cache ~/.stack
      with:
        path: ~/.stack
        key: ${{ runner.os }}-${{ matrix.stack-yaml }}-stack

    - name: Build
      run: |
        stack build \
          --stack-yaml ${{ matrix.stack-yaml }} \
          --flag myers-diff:diff \
          --flag myers-diff:uni_myers \
          --test --bench --no-run-tests --no-run-benchmarks

    - name: Test
      run: |
        stack test --stack-yaml ${{ matrix.stack-yaml }}
